[book]
title = "pyroxide"
description = "Fast, decoupled probabilistic programming in Rust"
authors = ["Jonathan Chen"]
language = "en"
src = "src"

[build]
build-dir = "../target/book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jpchen/pyroxide"
site-url = "/pyroxide/"

[output.html.fold]
enable = true
level = 1
